version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - laravel

  mariadb:
    image: mariadb:10.5
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laraveldb
    ports:
      - 3307:3306
    volumes:
      - ./db/:/var/lib/mysql/
    networks:
      - laravel

  php:
    build: ./php/.
    # image: masumonline/php-fpm-buster-8.1:6
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  npm:
    image: node:13.7
    user: "1000:1000"
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel

  artisan:
    image: masumonline/php-fpm-buster-8.1:latest
    # image: masumonline/php-fpm7.4
    container_name: artisan
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: [ '/var/www/html/artisan' ]
    networks:
      - laravel

  adminer:
    image: michalhosna/adminer
    restart: always
    ports:
      - 8077:8080
    environment:
      ADMINER_PASSWORD: secret
      ADMINER_SERVER: mariadb
      ADMINER_USERNAME: root
    networks:
      - laravel